#pragma config(Sensor, S3,     lightSensor,         sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "drivers/lego-light.h"
task main()
{
   wait1Msec(50);                        // The program waits 50 milliseconds to initialize the light sensor.
   while(true)                           // Infinite loop
   {
     int percentage = LSvalNorm(lightSensor);
     	nxtDisplayTextLine(2, "%d" ,percentage);
      if(percentage < 10)  // If the Light Sensor reads a value less than 45:
      {
        nxtDisplayTextLine(6, "Veo negro");                  // Motor C is run at a 20 power level.
      }
      else                               // If the Light Sensor reads a value greater than or equal to 45:
      {
        nxtDisplayTextLine(6, "Veo blanco");                 // Motor C is run at a 60 power level.
      }
   }
}
